In [1]:
import numpy as np

In [6]:
a=np.arange(100,200,10)
print(a)
a=a.reshape((5,2))
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [10]:
a=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
print(a)

print(a[::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]
