In [1]:
#importing numpy 
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)

6
(2, 3)
int64
2


In [6]:
#create array with constant value
print(np.zeros((5,5)))
print(np.ones((3,3)))
print(np.full((3,3),5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
#create array with constant value
print(np.random.random((3,4)))
print(np.random.randint(30,40,(3,4)))

[[0.05168691 0.46304643 0.20217882 0.52675644]
 [0.93469148 0.33733401 0.43237538 0.63722343]
 [0.88042419 0.95687554 0.82641455 0.46107129]]
[[32 37 38 31]
 [33 38 30 35]
 [34 37 30 35]]


In [11]:
#get values between given range and given step
a=np.arange(1,50,5)
print(a)

[ 1  6 11 16 21 26 31 36 41 46]


In [13]:
#get number of given values between give values
a=np.linspace(1,10,num=5) 
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [16]:
#reshaping of array
a=np.array([1,2,3,4,5,6])
a=a.reshape((2,3))
print(a)

a=a.reshape((1,-1))
print(a)

a=a.reshape((-1,1))
print(a)



[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
a=a.flatten()
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [18]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a*2)
print(a/2)
print(a+1)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[2 3 4]
 [5 6 7]]


In [19]:
#matrix transpose
a=np.random.randint(30,40,(3,4))
print(a.T)

[[38 36 32]
 [37 36 35]
 [33 38 35]
 [37 35 33]]


In [21]:
#maths in matrix
a=np.random.randint(30,40,(3,3))
b=a.T
print(np.matmul(a,b))

[[3269 3326 3596]
 [3326 3429 3679]
 [3596 3679 3969]]


In [24]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))

21
1
6


In [26]:
#to get min and max from matrix
a=np.array([[1,2,3],[4,5,6]])
#along columns
print(np.sum(a,axis=0))
print(np.min(a,axis=0))
print(np.max(a,axis=0))
#along rows
print(np.sum(a,axis=1))
print(np.min(a,axis=1))
print(np.max(a,axis=1))

[5 7 9]
[1 2 3]
[4 5 6]
[ 6 15]
[1 4]
[3 6]


In [27]:
#to sort 
a=np.array([[1,2,3],[4,5,6]])
print(np.sort(a))


[[1 2 3]
 [4 5 6]]


In [31]:
a=np.random.randint(1,100,(10,10))
print(a)

#a=a[1:5,2:7]
print(a[1:5,2:7])
print(a[:3,5:])

[[ 8 18 50 61 39 29 11 91 87 65]
 [49 73 27 10 98 72 76 10 42 15]
 [44 15 91 57  6 14 28 51 57 35]
 [65 62 47 50 29 13 68 61 30 76]
 [30 98 24 83 39 91 96 80 28 22]
 [22 89 27 41 87 93 57 79 28 38]
 [ 2 43 29  8 65 18 44 81 68 39]
 [12 87 90 52 63 57 82 48 96  9]
 [23  8  1 40 67 30 43 30 28 63]
 [ 7 32 98 19 48 89 30 84 35 18]]
[[27 10 98 72 76]
 [91 57  6 14 28]
 [47 50 29 13 68]
 [24 83 39 91 96]]
[[29 11 91 87 65]
 [72 76 10 42 15]
 [14 28 51 57 35]]


In [41]:
#slicing
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[::2,::2])
print(a[::2,::])
print(a[1:2,1:2])

[[1 3]
 [7 9]]
[[1 2 3]
 [7 8 9]]
[[5]]
