# This is tutorial 4 :
**NUMPY** array slicing

In [1]:
import numpy as np

In [2]:
matrix=np.arange(1,101).reshape(10,10)
print(matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
matrix[0,0]

1

In [5]:
x=matrix[:,0:2]
x

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

# Use of random in numpy

In [7]:
rand=np.random.random(1)
print(rand)

[0.87618128]


In [8]:
rand=np.random.randint(1,10, (3,3))
print(rand)

[[2 5 2]
 [6 1 9]
 [6 2 6]]


In [10]:
x=[1,2,3,4,5]
np.random.choice(x)

5