# This is tutorial 3 :

**Mathematical operations using numpy**

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr_add=np.add(arr1,arr2)
print(arr_add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
arr_sub=np.subtract(arr1, arr2)
print(arr_sub)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
arr_div=np.divide(arr1, arr2)
print(arr_div)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#matrix multiplication
mat_prod=arr1.dot(arr2)
print(mat_prod)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [9]:
arr1.max()

9

In [10]:
arr1.argmax()

8

In [12]:
#to find the max element within the row
print(arr1.max(axis=1))

[3 6 9]


In [13]:
#to find the max element within the column
print(arr1.max(axis=0))

[7 8 9]


In [14]:
print(arr1.mean(axis=0))

[4. 5. 6.]
