# This is tutorial 1: 

**Numpy-**
numpy is a scientific computing library.
supports large number of data like multidimentional array.
Use of mathematical operations like FT, random no capabilities.

In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)
print(arr_1d.ndim)     #dimensions of the array
print(arr_1d.size)     #size of the array
print(arr_1d.shape)    #shape of the array
print(arr_1d.dtype)    #datatype of the array

[1 2 3 4]
1
4
(4,)
int64


In [3]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
print(arr_2d.ndim)     #dimensions of the array
print(arr_2d.size)     #size of the array
print(arr_2d.shape)    #shape of the array
print(arr_2d.dtype)    #datatype of the array

[[1 2 3 4]
 [5 6 7 8]]
2
8
(2, 4)
int64


**Creating an array of ones and zeros**


In [4]:
arr_1s=np.ones((5,5), dtype= int)
print(arr_1s)
print(arr_1s.ndim)     #dimensions of the array
print(arr_1s.size)     #size of the array
print(arr_1s.shape)    #shape of the array
print(arr_1s.dtype)    #datatype of the array

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2
25
(5, 5)
int64


In [5]:

arr_bool=np.ones((5,5), dtype= bool)
print(arr_bool)
print(arr_bool.ndim)     #dimensions of the array
print(arr_bool.size)     #size of the array
print(arr_bool.shape)    #shape of the array
print(arr_bool.dtype)    #datatype of the array

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
2
25
(5, 5)
bool


In [6]:
arr_str=np.ones((5,5), dtype= str)
print(arr_str)
print(arr_str.ndim)     #dimensions of the array
print(arr_str.size)     #size of the array
print(arr_str.shape)    #shape of the array
print(arr_str.dtype)    #datatype of the array

arr_str=np.zeros((5,5), dtype= str)
print(arr_str)
print(arr_str.ndim)     #dimensions of the array
print(arr_str.size)     #size of the array
print(arr_str.shape)    #shape of the array
print(arr_str.dtype)    #datatype of the array

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]
2
25
(5, 5)
<U1
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
2
25
(5, 5)
<U1


In [7]:
'''To get the empty matrix.
We get garbage value inside the matrix.
'''
arr_emt=np.empty((3,3))
print(arr_emt)

[[2.29565508e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 3.95252517e-322]]
